[package]
name = "nand-flash-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
qoi = "0.4"
image = "0.25"
imageproc = { version = "0.26.1", features = ["text"] }
ab_glyph = "0.2"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
num_cpus = "1.16"
fltk = { version = "1.5.23", features = ["enable-glwindow"] }
egui = "0.27"
egui_glow = "0.27"
fltk-egui = "0.16"

[dev-dependencies]
proptest = "1.4"
tempfile = "3.8"

[target.'cfg(unix)'.dependencies]
fuser = { version = "0.14", default-features = false }
libc = "0.2"

[profile.dev]
opt-level = 3